### ISSUE TITLE
Complete loadouts

### ISSUE THREAD

**Issue by jerkinmerkin** [Spearhead-Gaming-Milsim/OP_Hand_of_God#1]
Switching over to the .sqf system on this mission.

**Comment by coachwn** [comment]
So honestly things like M4's didn't exist but you could give them M16A1/M203, M16A1 and M-60; maybe one or two sets of NVG's at the most...That is about the limit of what a high speed unit would have carried back then. Not that much variation from the regular soldiers just more

**Comment by jerkinmerkin** [comment]
So I'm looking at middle eastern countries in the early 80s for inspiration since we're playing as the Kingdom of Al-Rayak.  SOF standard issue is M16A1s, w/ M203s and a few startlight scopes and other optics.  Good ol' AKMs and then the L1A1 SLR since that's the standard issue rifle for Inf and Cav... probably give SOF  the chopmod version too.  Uzis / silencers because fuck yea.  M60 and MG3/MG42 as well.  No NVGs for anybody, but SOF will get a couple hand held starlight scopes.  SOF plus FTLs and above for everybody else will get flare guns.  At least this is the plan in my head.  Just started to put together Inf last night.

**Comment by jerkinmerkin** [comment]
Maybe startlight scopes to PLs and COs for all groups.

**Comment by coachwn** [comment]
If you are going middle eastern thoughts...why not move away from Uzi unless you just want to and push to the HK MP5SD since it might be a little difficult to think that a non-Israeli or US unit would be using an Uzi...just a thought; unless the weapons are already in the modpack together. I am assuming CUP weapons is the thing there?

**Comment by jerkinmerkin** [comment]
I'm using mostly Unsung assets, which is where I'm getting the Uzi and M16s and a whole bunch of other shit.  They're high quality so I know folks will like them.  It's a fictional country so there's a little bit of leeway with who gets what.  I'm not just taking inspiration from Arab countries but from Israel as well.  Even if I was just focusing of Arab countries, Syria pressed a lot of captured Uzis into service.

**Comment by jerkinmerkin** [comment]
So here's a quick summary of what I'm thinking based on the mods I'm working with.

Inf and Cav
Service Rifle: L1A1 SLR
GPMG: MG3
DMR: M14
AT: RPG-7

SOF
Service Rifle: M16A1
GPMG: M60
DMR: M14
Sniper: Don't know yet... haven't figured out anything yet that is both ACE compatable and ITF.
AT: RPG-18
Other: Uzi, MAC-10, L1A1 SLR, AKM

**Comment by Yakavetta** [comment]
M4's did exist as far back as Vietnam as the CAR-15, including adjustable length stock.  The version that would make the most sense for an SF unit would be a basic stripped down M4A1.  Here's a photo from 1968 showing a Cavalry LRS (not-SF unit) with them:
https://upload.wikimedia.org/wikipedia/commons/e/ec/Two_1st_Cav_LRP_teams.jpg

M249's also existed, albiet in XM233, form as far back as the early 70's which would definitely mean an SF team would have them.

But since we're playing as Al Rayak, and based on the teaser photo, this is reminiscent of the Iran/Iraq wars, it would make FAR more sense to have AK varients.  Keep in mind we didn't supply Iraq or Iran until after the wars.  Iran Contra was in the mid-80's, and we didn't equip Iraq until after the 2003 invasion.  Again, upload SQF's so we can have some oversight and work out the details of our kits with the time period correct.  This is exactly why I'm pushing for SQF, so we all can get more insight into our units loadouts, and ensure SOP compliance. If you push a repo, we can start making basic loadouts and work from there to iron them out.

**Comment by jerkinmerkin** [comment]
I have switched to SQFs on this mission.  I will post them for review as soon as I finish the load outs.
